// Code generated by protoc-gen-go.
// source: config.proto
// DO NOT EDIT!

/*
Package config is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	Config
*/
package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	// Hostname to use when we say hello.
	// For aesthetic purposes, but may help if our ip address resolves to it.
	// Default: machine hostname.
	Hostname string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	// Maximum email size, in megabytes.
	// Default: 50.
	MaxDataSizeMb int64 `protobuf:"varint,2,opt,name=max_data_size_mb,json=maxDataSizeMb" json:"max_data_size_mb,omitempty"`
	// Addresses to listen on for SMTP (usually port 25).
	// Default: "systemd", which means systemd passes sockets to us.
	// systemd sockets must be named with "FileDescriptorName=smtp".
	SmtpAddress []string `protobuf:"bytes,3,rep,name=smtp_address,json=smtpAddress" json:"smtp_address,omitempty"`
	// Addresses to listen on for submission (usually port 587).
	// Default: "systemd", which means systemd passes sockets to us.
	// systemd sockets must be named with "FileDescriptorName=submission".
	SubmissionAddress []string `protobuf:"bytes,4,rep,name=submission_address,json=submissionAddress" json:"submission_address,omitempty"`
	// Address for the monitoring http server.
	// Default: no monitoring http server.
	MonitoringAddress string `protobuf:"bytes,5,opt,name=monitoring_address,json=monitoringAddress" json:"monitoring_address,omitempty"`
	// Mail delivery agent (MDA, also known as LDA) to use.
	// This should point to the binary to use to deliver email to local users.
	// The content of the email will be passed via stdin.
	// If it exits unsuccessfully, we assume the mail was not delivered.
	// Default: "procmail".
	MailDeliveryAgentBin string `protobuf:"bytes,6,opt,name=mail_delivery_agent_bin,json=mailDeliveryAgentBin" json:"mail_delivery_agent_bin,omitempty"`
	// Command line arguments for the mail delivery agent. One per argument.
	// Some replacements will be done:
	//  - "%user%"   -> local user (anything before the @)
	//  - "%domain%" -> domain (anything after the @)
	// Default: "-d", "%user"  (adequate for procmail)
	MailDeliveryAgentArgs []string `protobuf:"bytes,7,rep,name=mail_delivery_agent_args,json=mailDeliveryAgentArgs" json:"mail_delivery_agent_args,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Config)(nil), "Config")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x2f, 0x04, 0x31,
	0x14, 0xc7, 0xb3, 0x3b, 0x0c, 0x6a, 0x25, 0xb6, 0x21, 0x1a, 0xa7, 0xe5, 0xc2, 0x85, 0x8b, 0x88,
	0xf3, 0xb0, 0x57, 0x97, 0xf5, 0x01, 0x9a, 0x57, 0x53, 0xf5, 0x92, 0xed, 0xeb, 0xa6, 0xaf, 0x04,
	0x1f, 0xce, 0x67, 0xd3, 0x29, 0x66, 0x24, 0xf6, 0x38, 0xbf, 0xdf, 0xef, 0x3f, 0x79, 0xa9, 0x98,
	0x3c, 0x06, 0x7a, 0x42, 0x77, 0xb9, 0x8a, 0x21, 0x85, 0xd3, 0xcf, 0xb1, 0xa8, 0xef, 0x0a, 0x90,
	0xc7, 0x62, 0xfb, 0x39, 0x70, 0x22, 0xf0, 0x56, 0x8d, 0x66, 0xa3, 0xf3, 0x9d, 0x45, 0xff, 0x2d,
	0xcf, 0xc4, 0xbe, 0x87, 0x37, 0xdd, 0x42, 0x02, 0xcd, 0xf8, 0x61, 0xb5, 0x37, 0x6a, 0x9c, 0x9b,
	0x6a, 0xb1, 0x97, 0xf9, 0x3c, 0xe3, 0x87, 0x4c, 0xef, 0x8d, 0x3c, 0x11, 0x13, 0xf6, 0x69, 0xa5,
	0xa1, 0x6d, 0xa3, 0x65, 0x56, 0xd5, 0xac, 0xca, 0x3f, 0xda, 0xed, 0x58, 0xf3, 0x8d, 0xe4, 0x85,
	0x90, 0xfc, 0x62, 0x3c, 0x32, 0x63, 0xa0, 0x3e, 0xdc, 0x28, 0xe1, 0x74, 0x30, 0x7f, 0x72, 0x1f,
	0x08, 0x53, 0x88, 0x48, 0xae, 0xcf, 0x37, 0xcb, 0x81, 0xd3, 0xc1, 0xfc, 0xe6, 0xd7, 0xe2, 0xc8,
	0x03, 0x2e, 0x75, 0x6b, 0x97, 0xf8, 0x6a, 0xe3, 0xbb, 0x06, 0x67, 0x29, 0x69, 0x83, 0xa4, 0xea,
	0xb2, 0x39, 0xe8, 0xf4, 0xfc, 0xc7, 0x36, 0x9d, 0xbc, 0x45, 0x92, 0x37, 0x42, 0xad, 0x9b, 0x41,
	0x74, 0xac, 0xb6, 0xca, 0x69, 0x87, 0xff, 0x76, 0x4d, 0x96, 0xa6, 0x2e, 0xef, 0x78, 0xf5, 0x15,
	0x00, 0x00, 0xff, 0xff, 0x23, 0xe3, 0xdb, 0x23, 0x57, 0x01, 0x00, 0x00,
}
